parameters:
    database_driver:   pdo_mysql
    database_host:     mysql.platformd.com
    database_port:     ~
    database_name:     platformd_campdb
    database_user:     kamalnayak
    database_password: sandip2451984

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    default_communityId: 1