<?php

namespace Campsite\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
  /**
   * find Session Based on Community
   * @param integer $limit No of Records to Display
   * @return QueryBuilder
   */
  public function findSessionByCommunity($communityId=1)
  {
    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('s')
        ->from('Campsite\AdminBundle\Entity\Session', 's')	
		->leftJoin('s.event','e')
		->leftJoin('e.groups','g')			
		->where('g.community=:id')
		->setParameter('id', $communityId);
		
		
	//echo $query = $qb->getQuery()->getSql();exit;
	$query = $qb->getQuery();
	return $query->getResult();
  }
  
  /**
   * find No of Votes And Session Details
   * @param integer $limit No of Records to Display
   * @return QueryBuilder
   */
  public function findSessionByEvent($eventId)
  {
    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('sum(utv.vote),s')
        //->from('Campsite\AdminBundle\Entity\UserTopicVote', 'utv')
        ->from('Campsite\AdminBundle\Entity\Session', 's')		
		->leftJoin('s.userTopicVote','utv')
		//->where('s.id = utv.session')
		//->groupBy('s.id');
		->Where('s.event=:id')
		//->orWhere('s.id = utv.session')
		->setParameter('id', $eventId)
		
		->groupBy('utv.session,s.event');
		
	//echo $query = $qb->getQuery()->getSql();exit;
	$query = $qb->getQuery();
	
	return $query->getResult();
  }
  
  public function getTotalVoteOfSession($sessionId)
  {
      $qb = $this->getEntityManager()->createQueryBuilder();
      $qb->select('sum(utv.vote)')
        ->from('Campsite\AdminBundle\Entity\UserTopicVote', 'utv')
        ->Where('utv.session=:id')
		//->orWhere('s.id = utv.session')
		->setParameter('id', $sessionId);
		
		
	//echo $query = $qb->getQuery()->getSql();exit;
	$query = $qb->getQuery();
	
	return $query->getResult();
  }
}