<?php

namespace Campsite\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * VendorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorsRepository extends EntityRepository
{
  /**
   * find All Sponcers
   * @param integer $limit No of Records to Display
   * @return QueryBuilder
   */
  public function findAllSponcers()
  {
   $qb = $this->getEntityManager()->createQueryBuilder();
   $qb->select('ev,v')
        ->from('Campsite\AdminBundle\Entity\EventsVendors', 'ev')
    	->leftJoin('ev.vendor','v')
		->where('ev.type=:type')
		->setParameter('type',1);
	$query = $qb->getQuery();	
    return $query->getResult();
  }
  
  /**
   * find All Partners
   * @param integer $limit No of Records to Display
   * @return QueryBuilder
   */
  public function findAllPartners()
  {
   $qb = $this->getEntityManager()->createQueryBuilder();
   $qb->select('ev,v')
        ->from('Campsite\AdminBundle\Entity\EventsVendors', 'ev')
    	->leftJoin('ev.vendor','v')
		->where('ev.type=:type')
		->setParameter('type',2);
	$query = $qb->getQuery();		
    return $query->getResult();
  }
  
}